# Generated by Django 3.2.4 on 2021-12-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, default='Anonymous', max_length=50, verbose_name='User Name')),
                ('password', models.CharField(db_index=True, default='Anonymous', max_length=500, verbose_name='Password')),
                ('email', models.EmailField(db_index=True, default='Anonymous', max_length=254, verbose_name='Email')),
                ('token', models.CharField(default='Anonymous', max_length=500, verbose_name='Token')),
                ('token_expires_at', models.DateTimeField(auto_now=True, verbose_name='Token Expires At')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
            ],
        ),
    ]
