# Generated by Django 3.2.4 on 2021-12-08 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211208_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(db_index=True, default='UserName', max_length=50, verbose_name='User Name'),
        ),
    ]
