# Generated by Django 3.2.4 on 2021-12-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Created at'),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, default='Anonymous', max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='user',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified at'),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(db_index=True, default='Anonymous', max_length=500, verbose_name='Password'),
        ),
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(default='Anonymous', max_length=500, verbose_name='Token'),
        ),
        migrations.AddField(
            model_name='user',
            name='token_expires_at',
            field=models.DateTimeField(default='Anonymous', verbose_name='Token Expires At'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, default='Anonymous', max_length=50, verbose_name='User Name'),
        ),
    ]
