# Generated by Django 3.2.4 on 2021-12-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20211207_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token_expires_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Token Expires At'),
        ),
    ]
