# Generated by Django 3.2.4 on 2021-12-07 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='House',
        ),
    ]
