# To use the http client, install "REST Client" extension of Visual Studio Code.
# To send the request and get the result, click the 'Send Request' 
POST http://127.0.0.1:8000/sellrequest/add/ HTTP/1.1
content-type: application/json
Authorization: ef352cccc3dbea99841f5101b494e1f5cc34c5980e388ceba3185eaee6de

{
	"address": "rajit@gmail.com",
	"sqft": "12345",
    "age_building": 4555
}