# To use the http client, install "REST Client" extension of Visual Studio Code.
# To send the request and get the result, click the 'Send Request' 
POST http://127.0.0.1:8000/users/signin/ HTTP/1.1
content-type: application/json
Authorization: 64316adcbb8c99dda867ed0d5e6dfed74bf56645582a739195fe100176cb

{
	"email": "rajit@gmail.com",
	"password": "12345"
}